apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-spring-app-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 8
  selector:
    matchLabels:
      env: development
  template:
    metadata:
      name: basic-spring-app
      labels:
        env: development
    spec:
      containers:
        - name: basic-spring-app
          image: hakaneroztekin/basic-spring-app
          ports:
            - containerPort: 8080