apiVersion: v1
kind: Pod
metadata:
  name: basic-spring-app
  labels:
    env: development
spec:
  containers:
    - name: basic-spring-app
      image: hakaneroztekin/basic-spring-app
      ports:
        - containerPort: 8080